[package]
name = "kdbx"
version = "0.1.0"
edition = "2018"

[lib]
crate_type = ["staticlib", "dylib"]

[dependencies]
jni = "0.19.0"
byteorder = "1"
thiserror = "1"
sha2 = "0.9.8"
hmac = "0.11.0"
rust-argon2 = "0.8"